name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run linter
        run: |
          poetry run flake8 brain_games
